<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="PRG_TEST" Id="{89d6d83b-e661-4729-8376-220f86d31845}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'no-analysis'}       // Disable SA for entire POU
PROGRAM PRG_TEST
VAR
    {attribute 'analysis' := '-33'}      // Disable SA0033: Unused variable
    _StringBuilder_Test : StringBuilder_Test;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//TcUnit.RUN();
TcUnit.RUN_IN_SEQUENCE();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>